In [1]:
import numpy as np

In [8]:
a = np.arange(5)
b = np.arange(2, 11, step=2)

# addition

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
b

array([ 2,  4,  6,  8, 10])

In [11]:
a + b

array([ 2,  5,  8, 11, 14])

In [12]:
a + 5

array([5, 6, 7, 8, 9])

In [13]:
np.add(a, b)

array([ 2,  5,  8, 11, 14])

In [14]:
np.add(a, 4)

array([4, 5, 6, 7, 8])

# subtraction

In [15]:
a - b

array([-2, -3, -4, -5, -6])

In [16]:
b - a

array([2, 3, 4, 5, 6])

In [17]:
a - 5

array([-5, -4, -3, -2, -1])

In [18]:
np.subtract(a, b)

array([-2, -3, -4, -5, -6])

In [19]:
np.subtract(a, 5)

array([-5, -4, -3, -2, -1])

# multiplication

In [20]:
a * b

array([ 0,  4, 12, 24, 40])

In [21]:
a * 2

array([0, 2, 4, 6, 8])

In [22]:
np.multiply(a, b)

array([ 0,  4, 12, 24, 40])

In [23]:
np.multiply(a, 2)

array([0, 2, 4, 6, 8])

# division

In [25]:
b / a 

/var/folders/2k/fztkts0j2yl603hc8vbyrf540000gn/T/ipykernel_74843/1318104181.py:1: RuntimeWarning: divide by zero encountered in divide
  b / a


array([       inf, 4.        , 3.        , 2.66666667, 2.5       ])

In [26]:
b / 2

array([1., 2., 3., 4., 5.])

In [27]:
b / 3

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [28]:
np.divide(b, a)

/var/folders/2k/fztkts0j2yl603hc8vbyrf540000gn/T/ipykernel_74843/2227768009.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(b, a)


array([       inf, 4.        , 3.        , 2.66666667, 2.5       ])

In [29]:
np.divide(b, 2)

array([1., 2., 3., 4., 5.])

In [30]:
np.divide(b, 3)

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [31]:
b // 3

array([0, 1, 2, 2, 3])

In [32]:
b % 3

array([2, 1, 0, 2, 1])

In [33]:
# np.mod() = %
np.mod(b, 3)

array([2, 1, 0, 2, 1])

# power and squared root

In [34]:
np.power(2, 3)

8

In [35]:
2 ** 3

8

In [36]:
a = np.arange(1, 11, 1)
b = np.tile([1, 2], reps=5)

In [37]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
b

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [39]:
np.power(a, b)

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100])

In [40]:
a ** b

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100])

In [41]:
np.sqrt(2)

1.4142135623730951

In [42]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

# exponential

In [43]:
np.exp(1)

2.718281828459045

In [44]:
np.exp(2)

7.38905609893065

In [45]:
np.exp(0)

1.0

# Logarithm (log)

np.log(): log with e as base

In [46]:
np.log(np.e)  # should be 1

1.0

In [47]:
a = np.array([1, 2, np.e**2, 10])

In [48]:
np.log(a)

array([0.        , 0.69314718, 2.        , 2.30258509])

np.log2(): log with 2 as base

In [51]:
np.log2(2) # should be 1

1.0

In [49]:
b = np.array([1,2,4,7])

In [52]:
np.log2(b)

array([0.        , 1.        , 2.        , 2.80735492])

np.log10(): log with 10 as base

In [53]:
c = np.array([1, 10, 20, 30])

In [54]:
np.log10(c)

array([0.        , 1.        , 1.30103   , 1.47712125])

np.log1p(x): np.log(1 + x)

In [55]:
np.log1p(a)

array([0.69314718, 1.09861229, 2.12692801, 2.39789527])

In [56]:
np.log(a+1)

array([0.69314718, 1.09861229, 2.12692801, 2.39789527])

In [57]:
np.log(2) / np.log(4)

0.5

In [59]:
np.log(9) / np.log(3)

2.0

# round numbers

In [62]:
a = np.random.randn(11) * np.random.choice([-1, 1], 11)

In [63]:
a

array([ 0.60503639, -1.56566013, -0.64010726,  2.22226742, -0.33059032,
        0.35479007, -0.43422831, -1.39897223, -2.35100969, -0.71973293,
        1.55336253])

np.floor()

In [64]:
np.floor(a)

array([ 0., -2., -1.,  2., -1.,  0., -1., -2., -3., -1.,  1.])

np.trunc(): remove all decimals

In [65]:
np.trunc(a)

array([ 0., -1., -0.,  2., -0.,  0., -0., -1., -2., -0.,  1.])

np.ceil()

In [66]:
np.ceil(a)

array([ 1., -1., -0.,  3., -0.,  1., -0., -1., -2., -0.,  2.])

np.round() = np.around()

In [67]:
np.round(a)

array([ 1., -2., -1.,  2., -0.,  0., -0., -1., -2., -1.,  2.])

In [68]:
np.around(a)

array([ 1., -2., -1.,  2., -0.,  0., -0., -1., -2., -1.,  2.])

np.rint()

In [69]:
np.rint(a)

array([ 1., -2., -1.,  2., -0.,  0., -0., -1., -2., -1.,  2.])

np.fix(): choose integers closer to 0

In [70]:
np.fix(a)

array([ 0., -1., -0.,  2., -0.,  0., -0., -1., -2., -0.,  1.])

# absolute value

In [71]:
a = -2.5

when dealing with real numbers,

np.absolute() = np.abs() = np.fabs()


In [72]:
np.absolute(a)

2.5

In [73]:
np.fabs(a)

2.5

when dealing with complex numbers,

np.fabs() != np.abs()

In [74]:
b = -2 + 3j

In [75]:
np.abs(b)

3.6055512754639896

In [77]:
try:
    np.fabs(b)
except TypeError as e:
    print(e)

ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''


In [78]:
c = np.array([-1, 2, -8, 12, 1+2j])

In [79]:
np.abs(c)

array([ 1.        ,  2.        ,  8.        , 12.        ,  2.23606798])

# average

### np.average(): support weighted average

In [80]:
a = np.random.randint(20, 60, 8)
a

array([42, 44, 26, 31, 46, 54, 32, 35])

In [81]:
np.average(a)

38.75

In [82]:
a = a.reshape(2, 4)
a

array([[42, 44, 26, 31],
       [46, 54, 32, 35]])

In [83]:
np.average(a)

38.75

axis

In [84]:
np.average(a, axis=0)

array([44., 49., 29., 33.])

In [85]:
np.average(a, axis=1)

array([35.75, 41.75])

In [86]:
b = np.random.rand(24).reshape(2, 3, 4)
b

array([[[0.15908112, 0.79077752, 0.98914009, 0.70493735],
        [0.8707861 , 0.31665579, 0.34809705, 0.05467492],
        [0.69263713, 0.23266425, 0.44192561, 0.17132968]],

       [[0.43034003, 0.84599375, 0.67452678, 0.90204028],
        [0.01793562, 0.08944062, 0.91462821, 0.31665303],
        [0.97911732, 0.79377964, 0.77694508, 0.36223462]]])

In [87]:
np.average(b, axis=0)

array([[0.29471057, 0.81838563, 0.83183344, 0.80348881],
       [0.44436086, 0.20304821, 0.63136263, 0.18566397],
       [0.83587722, 0.51322194, 0.60943534, 0.26678215]])

In [88]:
np.average(b, axis=1)

array([[0.57416811, 0.44669919, 0.59305425, 0.31031398],
       [0.47579766, 0.57640467, 0.78870002, 0.52697597]])

In [89]:
np.average(b, axis=2)

array([[0.66098402, 0.39755346, 0.38463917],
       [0.71322521, 0.33466437, 0.72801916]])

weights

In [90]:
a = a.flatten()
a

array([42, 44, 26, 31, 46, 54, 32, 35])

In [91]:
w = np.array([0.1, 0.05, 0.2, 0.0, 0.0, 0.4, 0.2, 0.05])
w

array([0.1 , 0.05, 0.2 , 0.  , 0.  , 0.4 , 0.2 , 0.05])

In [92]:
np.average(a, weights=w)

41.35

In [93]:
np.average(a)

38.75

In [94]:
w2 = np.array([0.2, 0.8])
w2

array([0.2, 0.8])

In [95]:
a = a.reshape(2, 4)
a

array([[42, 44, 26, 31],
       [46, 54, 32, 35]])

In [96]:
np.average(a, axis=0, weights=w2)

array([45.2, 52. , 30.8, 34.2])

In [97]:
np.average(a, axis=0)

array([44., 49., 29., 33.])

returned

if True, return the total sum of weights

In [98]:
np.average(a, returned=True)

(38.75, 8.0)

In [99]:
a = a.flatten()
a

array([42, 44, 26, 31, 46, 54, 32, 35])

In [100]:
w

array([0.1 , 0.05, 0.2 , 0.  , 0.  , 0.4 , 0.2 , 0.05])

In [101]:
np.average(a, weights=w, returned=True)

(41.35, 1.0)

### np.mean(): not support weights, but support dtype and keepdims

In [102]:
np.random.seed(1)
a = np.random.randint(0, 10, 20)
a

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9, 2, 4, 5, 2, 4, 2, 4, 7, 7, 9])

In [103]:
np.mean(a)

4.8

In [104]:
a.mean()

4.8

In [105]:
b = a.reshape(4, 5)
b

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4],
       [2, 4, 7, 7, 9]])

In [106]:
np.mean(b)

4.8

In [107]:
b.mean()

4.8

axis

In [108]:
np.mean(b, axis=0)

array([2.25, 4.25, 7.  , 5.  , 5.5 ])

In [109]:
np.mean(b, axis=1)

array([5.4, 4.6, 3.4, 5.8])

In [110]:
c = np.random.rand(24).reshape((2, 3, 4))
c

array([[[0.43069857, 0.93912779, 0.77838924, 0.71597052],
        [0.8027575 , 0.09280081, 0.51815255, 0.86502025],
        [0.82914691, 0.82960336, 0.27304997, 0.0592432 ]],

       [[0.67052804, 0.59306552, 0.6716541 , 0.41178788],
        [0.1975509 , 0.28962964, 0.14212014, 0.78331447],
        [0.41253884, 0.03417131, 0.62402999, 0.66063573]]])

In [111]:
np.mean(c, axis=0)

array([[0.5506133 , 0.76609665, 0.72502167, 0.5638792 ],
       [0.5001542 , 0.19121522, 0.33013634, 0.82416736],
       [0.62084287, 0.43188734, 0.44853998, 0.35993947]])

In [112]:
np.mean(c, axis=1)

array([[0.68753433, 0.62051065, 0.52319725, 0.54674466],
       [0.42687259, 0.30562216, 0.47926807, 0.61857936]])

In [113]:
np.mean(c, axis=2)

array([[0.71604653, 0.56968278, 0.49776086],
       [0.58675888, 0.35315379, 0.43284397]])

keepdims

In [114]:
b

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4],
       [2, 4, 7, 7, 9]])

In [115]:
e = np.mean(b, keepdims=True)
e

array([[4.8]])

In [116]:
e.shape

(1, 1)

In [117]:
f = np.mean(b, keepdims=False)
f

4.8

In [118]:
g = np.mean(b, axis=1, keepdims=True)
g

array([[5.4],
       [4.6],
       [3.4],
       [5.8]])

In [119]:
g.shape

(4, 1)

In [120]:
h = np.mean(b, axis=1, keepdims=False)
h

array([5.4, 4.6, 3.4, 5.8])

In [121]:
h.shape

(4,)