In [1]:
import numpy as np

In [8]:
a = np.arange(5)
b = np.arange(2, 11, step=2)

# addition

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
b

array([ 2,  4,  6,  8, 10])

In [11]:
a + b

array([ 2,  5,  8, 11, 14])

In [12]:
a + 5

array([5, 6, 7, 8, 9])

In [13]:
np.add(a, b)

array([ 2,  5,  8, 11, 14])

In [14]:
np.add(a, 4)

array([4, 5, 6, 7, 8])

# subtraction

In [15]:
a - b

array([-2, -3, -4, -5, -6])

In [16]:
b - a

array([2, 3, 4, 5, 6])

In [17]:
a - 5

array([-5, -4, -3, -2, -1])

In [18]:
np.subtract(a, b)

array([-2, -3, -4, -5, -6])

In [19]:
np.subtract(a, 5)

array([-5, -4, -3, -2, -1])

# multiplication

In [20]:
a * b

array([ 0,  4, 12, 24, 40])

In [21]:
a * 2

array([0, 2, 4, 6, 8])

In [22]:
np.multiply(a, b)

array([ 0,  4, 12, 24, 40])

In [23]:
np.multiply(a, 2)

array([0, 2, 4, 6, 8])

# division

In [25]:
b / a 

/var/folders/2k/fztkts0j2yl603hc8vbyrf540000gn/T/ipykernel_74843/1318104181.py:1: RuntimeWarning: divide by zero encountered in divide
  b / a


array([       inf, 4.        , 3.        , 2.66666667, 2.5       ])

In [26]:
b / 2

array([1., 2., 3., 4., 5.])

In [27]:
b / 3

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [28]:
np.divide(b, a)

/var/folders/2k/fztkts0j2yl603hc8vbyrf540000gn/T/ipykernel_74843/2227768009.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(b, a)


array([       inf, 4.        , 3.        , 2.66666667, 2.5       ])

In [29]:
np.divide(b, 2)

array([1., 2., 3., 4., 5.])

In [30]:
np.divide(b, 3)

array([0.66666667, 1.33333333, 2.        , 2.66666667, 3.33333333])

In [31]:
b // 3

array([0, 1, 2, 2, 3])

In [32]:
b % 3

array([2, 1, 0, 2, 1])

In [33]:
# np.mod() = %
np.mod(b, 3)

array([2, 1, 0, 2, 1])

# power and squared root

In [34]:
np.power(2, 3)

8

In [35]:
2 ** 3

8

In [36]:
a = np.arange(1, 11, 1)
b = np.tile([1, 2], reps=5)

In [37]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
b

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [39]:
np.power(a, b)

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100])

In [40]:
a ** b

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100])

In [41]:
np.sqrt(2)

1.4142135623730951

In [42]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])