In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
X = np.array([[1, 2], [3, 4], [5, 6]])
X_pt = torch.from_numpy(X)
X_tf = tf.Variable([[1, 2], [3, 4], [5, 6]])

In [12]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
X * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [4]:
X + 2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [5]:
X * 2 + 2

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

In [6]:
X_pt * 2 + 2 # Python operators are overloaded, but allowed alternatively to use torch.mul() for multiplication or torch.add() for addition

tensor([[ 4,  6],
        [ 8, 10],
        [12, 14]])

In [7]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[ 4,  6],
        [ 8, 10],
        [12, 14]])

In [8]:
X_tf * 2 + 2 # Operators likewise overloaded, and allowed alternatively to use tf.multiply() for multiplication or tf.add() for addition

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 8, 10],
       [12, 14]], dtype=int32)>

In [10]:
tf.add(tf.multiply(X_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 8, 10],
       [12, 14]], dtype=int32)>

**Hadamard Product** (element-wise product)

In [11]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
A = X + 2
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [14]:
A + X

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

In [15]:
A * X

array([[ 3,  8],
       [15, 24],
       [35, 48]])

In [16]:
A_pt = X_pt + 2
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [17]:
A_pt + X_pt

tensor([[ 4,  6],
        [ 8, 10],
        [12, 14]])

In [18]:
A_pt * X_pt

tensor([[ 3,  8],
        [15, 24],
        [35, 48]])

In [19]:
A_tf = X_tf + 2
A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [20]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 8, 10],
       [12, 14]], dtype=int32)>

In [21]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  8],
       [15, 24],
       [35, 48]], dtype=int32)>