In [1]:
import numpy as np

# np.convolve()

In [3]:
a = np.arange(6)
v = np.array([0.2, 0.8])

mode = full

In [5]:
np.convolve(a, v, mode='full')

array([0. , 0.2, 1.2, 2.2, 3.2, 4.2, 4. ])

mode = same

In [6]:
np.convolve(a, v, mode='same')

array([0. , 0.2, 1.2, 2.2, 3.2, 4.2])

mode = valid

In [7]:
np.convolve(a, v, mode='valid')

array([0.2, 1.2, 2.2, 3.2, 4.2])