In [1]:
import numpy as np

# np.cross()

In [2]:
a = np.array([1, 2, 3])
b = np.array([5, 5, 0])

In [3]:
np.cross(a, b)

array([-15,  15,  -5])

In [4]:
c = np.array([-1, 2, -3])
d = np.array([4, -5, 6])

In [5]:
np.cross(c, d)

array([-3, -6, -3])

auto convert into 3 dimensional space if arrays are in 2 dimensional space

In [6]:
e = np.array([5, 5])

In [7]:
np.cross(a, e)

array([-15,  15,  -5])

calculate multiple cross products at the same time using np.vstack()

In [9]:
ac = np.vstack((a, c))
bd = np.vstack((b, d))

In [10]:
ac

array([[ 1,  2,  3],
       [-1,  2, -3]])

In [11]:
bd

array([[ 5,  5,  0],
       [ 4, -5,  6]])

In [13]:
# the result will be aXb, cXd
np.cross(ac, bd)

array([[-15,  15,  -5],
       [ -3,  -6,  -3]])

axisa

In [14]:
ac.T

array([[ 1, -1],
       [ 2,  2],
       [ 3, -3]])

In [16]:
try:
    np.cross(ac.T, bd)
except ValueError as e:
    print(e)

shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3,) and arg 1 with shape (2,).


In [17]:
# define a new array from array a, which is ac.T, along with axis 0 (i.e. the direction of row)
np.cross(ac.T, bd, axisa=0)

array([[-15,  15,  -5],
       [ -3,  -6,  -3]])

axisb

In [18]:
bd.T

array([[ 5,  4],
       [ 5, -5],
       [ 0,  6]])

In [19]:
# define a new array from array b, which is bd.T, along with axis 0 (i.e. the direction of row)
np.cross(ac, bd.T, axisb=0)

array([[-15,  15,  -5],
       [ -3,  -6,  -3]])

axisc: control the returned format

In [20]:
np.cross(ac, bd, axisc=1)

array([[-15,  15,  -5],
       [ -3,  -6,  -3]])

In [21]:
np.cross(ac, bd, axisc=0)

array([[-15,  -3],
       [ 15,  -6],
       [ -5,  -3]])

axis

In [22]:
np.cross(ac.T, bd.T, axis=0)

array([[-15,  -3],
       [ 15,  -6],
       [ -5,  -3]])

dimension must be 2 or 3

incompatible with 1 dimensional or higher dimensional arrays' cross products

In [23]:
try:
    np.cross(np.ones(4), np.ones(4))
except ValueError as e:
    print(e)

incompatible dimensions for cross product
(dimension must be 2 or 3)


In [24]:
try:
    np.cross(np.array([1]), np.array([1]))
except ValueError as e:
    print(e)

incompatible dimensions for cross product
(dimension must be 2 or 3)


In [25]:
try:
    np.cross(np.ones(4), np.array([1]))
except ValueError as e:
    print(e)

incompatible dimensions for cross product
(dimension must be 2 or 3)
