In [1]:
import numpy as np
import torch
import tensorflow as tf

2023-11-09 17:04:03.786751: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


If we have two vectors (e.g. **x** and **y**) with the same length _n_, we can calculate the dot product between them. This is annotated several different ways, including the following:

*   $x \cdot y$
*   $x^Ty$
*   $\langle x, y \rangle$

Regardless which notation we use, the calculation is the same; we calculate products in an element-wise fashion and then sum reductively across the products to a scalar value. That is, $x\cdot y = \sum_{i=1}^{n} x_iy_i$

Ths dot product is ubiquitous in deep learning: It is performed at every artificial neuron in a deep neural network, which may be made up of millions (or orders of magnitude more) of these neurons.


In [2]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [3]:
y = np.array([0, 1, 2])
y

array([0, 1, 2])

In [4]:
1 * 0 + 2 * 1 + 3 * 2

8

In [5]:
np.dot(x, y)

8

In [6]:
x_pt = torch.tensor([1, 2, 3])
x_pt

tensor([1, 2, 3])

In [7]:
y_pt = torch.tensor([0, 1, 2])
y_pt

tensor([0, 1, 2])

In [8]:
np.dot(x_pt, y_pt)

8

In [9]:
torch.dot(torch.tensor([1, 2, 3]), torch.tensor([0, 1, 2]))

tensor(8)

In [10]:
x_tf = tf.Variable([1, 2 ,3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [11]:
y_tf = tf.Variable([0, 1, 2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [12]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

# dot product

dot product in numpy can be applied to both inner product of arrays and matrix multiplication

In [2]:
a = np.array([1, 2])
b = np.array([4, 3])

In [3]:
np.dot(a, b)

10

In [4]:
np.dot(4, 5)

20

np.matrix() can be used to create 2-D arrays

In [5]:
e = np.matrix([1, 2])
e

matrix([[1, 2]])

In [7]:
f = np.matrix([4, 3])
f.shape

(1, 2)

In [8]:
f = np.matrix([[4], [3]])
f.shape

(2, 1)

In [9]:
f

matrix([[4],
        [3]])

In [10]:
np.dot(e, f)

matrix([[10]])

In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
b

array([[4, 3],
       [2, 1]])

In [12]:
np.dot(a, b)

array([[ 8,  5],
       [20, 13]])

In [13]:
np.dot(b, a)

array([[13, 20],
       [ 5,  8]])

In [14]:
c = np.arange(9).reshape(3, 3)
d = np.ones((3, 3))

In [18]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.dot(c, d)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [23]:
a = np.matrix([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])
b = np.matrix([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])

In [24]:
a

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [25]:
b

matrix([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [26]:
np.dot(a, b)

matrix([[ 3,  3,  3],
        [12, 12, 12],
        [21, 21, 21]])