In [1]:
import numpy as np
import torch
import tensorflow as tf

If we have two vectors (e.g. **x** and **y**) with the same length _n_, we can calculate the dot product between them. This is annotated several different ways, including the following:

*   $x \cdot y$
*   $x^Ty$
*   $\langle x, y \rangle$

Regardless which notation we use, the calculation is the same; we calculate products in an element-wise fashion and then sum reductively across the products to a scalar value. That is, $x\cdot y = \sum_{i=1}^{n} x_iy_i$

Ths dot product is ubiquitous in deep learning: It is performed at every artificial neuron in a deep neural network, which may be made up of millions (or orders of magnitude more) of these neurons.


In [2]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [3]:
y = np.array([0, 1, 2])
y

array([0, 1, 2])

In [4]:
1 * 0 + 2 * 1 + 3 * 2

8

In [5]:
np.dot(x, y)

8

In [6]:
x_pt = torch.tensor([1, 2, 3])
x_pt

tensor([1, 2, 3])

In [7]:
y_pt = torch.tensor([0, 1, 2])
y_pt

tensor([0, 1, 2])

In [8]:
np.dot(x_pt, y_pt)

8

In [9]:
torch.dot(torch.tensor([1, 2, 3]), torch.tensor([0, 1, 2]))

tensor(8)

In [10]:
x_tf = tf.Variable([1, 2 ,3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [11]:
y_tf = tf.Variable([0, 1, 2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [12]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=8>