In [1]:
import numpy as np
import torch
import tensorflow as tf
import matplotlib.pyplot as plt

The **eigendecomposition** of some matrix $A$ is

$A=VΛV^{-1}$

Where:

*   As in example above, $V$ is the concatenation of all the eigenvectors of $A$
*   Λ (upper-case λ) is the diagonal matrix diag(λ). Note that the convention is to arrange the lambda values in descending order; as a result, the first eigenvalue (and its associated eigenvector) may be a primary characteristic of the matrix $A$.



In [2]:
A = np.array([[4, 2], [-5, -3]])
A

array([[ 4,  2],
       [-5, -3]])

In [3]:
lambdas, V = np.linalg.eig(A)

In [4]:
V

array([[ 0.70710678, -0.37139068],
       [-0.70710678,  0.92847669]])

In [5]:
V_inv = np.linalg.inv(V)
V_inv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [6]:
Lambda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

Confirm that $A=VΛV^{-1}$

In [7]:
np.dot(V, np.dot(Lambda, V_inv))

array([[ 4.,  2.],
       [-5., -3.]])

Eigendecomposition is not possible with all matrices. And in some cases where it is possible, the eigendecomposition involves complex numbers instead of straightforward read numbers.

In machine learning, however, we are typically working with real symmetric matrices, which can be conveniently and efficiently decomposed into real-only eigenvectors and real-only eigenvalues. If $A$ is a real symmetric matrix then

$A=QΛQ^T$

where $Q$ is analogous to $V$ from the previous equation except that it's special because it's an orthogonal matrix.

In [13]:
A = np.array([[2, 1], [1, 2]])
A

array([[2, 1],
       [1, 2]])

In [14]:
lambdas, Q = np.linalg.eig(A)

In [15]:
lambdas

array([3., 1.])

In [16]:
Lmabda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

In [17]:
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

Confirm that $A=QΛQ^T$

In [18]:
np.dot(Q, np.dot(Lambda, Q.T))

array([[0.5, 1.5],
       [1.5, 0.5]])

In [19]:
np.dot(Q.T, Q)

array([[1.00000000e+00, 2.23711432e-17],
       [2.23711432e-17, 1.00000000e+00]])

In [20]:
np.dot(Q, Q.T)

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])



1.   Use PyTorch to decompose the matrix $P$ (below) into its components $V, Λ, and V^{-1}$. Comfirm that $P=VΛV^{-1}$
2.   Use PyTorch to decompose the symmetric matrix $S$ (below) into its components $Q, Λ, and Q^T$. Comfirm that $S=QΛQ^T$.



In [21]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [22]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])