In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [3]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [4]:
torch.matmul(I, x_pt)

tensor([25,  2,  5])