In [1]:
import numpy as np
import torch
import tensorflow as tf

Matrix Multiplication (with Vector)

In [2]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
b = np.array([1, 2])
b

array([1, 2])

In [6]:
np.matmul(A, b)

array([ 5, 11, 17])

In [7]:
np.dot(A, b)

array([ 5, 11, 17])

In [9]:
np.all(np.matmul(A, b) == np.dot(A, b))

True

In [4]:
A_pt = torch.tensor([[1, 2], [3, 4], [5, 6]])
A_pt

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
b_pt = torch.tensor([1, 2])
b_pt

tensor([1, 2])

In [10]:
torch.matmul(A_pt, b_pt)

tensor([ 5, 11, 17])

In [11]:
A_tf = tf.Variable([[1, 2], [3, 4], [5, 6]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [12]:
b_tf = tf.Variable([1, 2])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [13]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 11, 17], dtype=int32)>

Matrix Multiplication (with Two Matrices)

In [14]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
B = np.array([[1, 0], [0, 1]])
B

array([[1, 0],
       [0, 1]])

In [17]:
np.matmul(A, B)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
np.dot(A, B)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.all(np.matmul(A, B) == np.dot(A, B))

True

In [20]:
B_pt = torch.from_numpy(B)
B_pt

tensor([[1, 0],
        [0, 1]])

In [22]:
torch.matmul(A_pt, B_pt)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

In [24]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>