In [1]:
import numpy as np
import torch
import tensorflow as tf

Matrices (Rank 2 Tensors) in NumPy

In [4]:
# Use array() with nested brackets
X = np.array([[1, 2], [3, 4], [5, 6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
X.shape

(3, 2)

In [6]:
X.size

6

In [8]:
# Select left column of matrix X (zero-indexed)
X[:, 0]

array([1, 3, 5])

In [9]:
# Select middle row of matrix X
X[1, :]

array([3, 4])

In [10]:
# Another slicing-by-index example
X[0:2, 0:2]

array([[1, 2],
       [3, 4]])

Matrices in PyTorch

In [11]:
X_pt = torch.tensor([[1, 2], [3, 4], [5, 6]])
X_pt

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
X_pt.shape # more pythonic

torch.Size([3, 2])

In [13]:
X_pt[1, :]

tensor([3, 4])

Matrices in TensorFlow

In [14]:
X_tf = tf.Variable([[1, 2], [3, 4], [5, 6]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [15]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [17]:
X_tf[1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>