In [1]:
import numpy as np

# z-score normalisation (standardisation)

In [2]:
def zscore(x, axis=None):
    xmean = x.mean(axis=axis, keepdims=True)
    xstd = np.std(x, axis=axis, keepdims=True)
    zscore = (x - xmean) / xstd
    return zscore 

In [3]:
a = np.random.randint(10, size=(2, 5))
a

array([[0, 5, 7, 4, 4],
       [1, 1, 9, 4, 7]])

In [4]:
zscore(a)

array([[-1.50771213,  0.28718326,  1.00514142, -0.07179582, -0.07179582],
       [-1.14873305, -1.14873305,  1.72309958, -0.07179582,  1.00514142]])

In [5]:
zscore(a, axis=1)

array([[-1.75411604,  0.43852901,  1.31558703,  0.        ,  0.        ],
       [-1.0625    , -1.0625    ,  1.4375    , -0.125     ,  0.8125    ]])

# min-max normalisation

In [6]:
def min_max(x, axis=None):
    min = x.min(axis=axis, keepdims=True)
    max = x.max(axis=axis, keepdims=True)
    result = (x - min) / (max - min)
    return result

In [7]:
b = np.random.randint(10, size=(2, 5))
b

array([[7, 0, 3, 3, 0],
       [3, 4, 0, 8, 9]])

In [8]:
min_max(b)

array([[0.77777778, 0.        , 0.33333333, 0.33333333, 0.        ],
       [0.33333333, 0.44444444, 0.        , 0.88888889, 1.        ]])

In [9]:
min_max(b, axis=1)

array([[1.        , 0.        , 0.42857143, 0.42857143, 0.        ],
       [0.33333333, 0.44444444, 0.        , 0.88888889, 1.        ]])