In [1]:
import numpy as np
import torch
import tensorflow as tf

$L^2$ Norm:  \|\| x \|\|$_2$ = \|\| x \|\|

Measuring simple Euclidean distance from origin

Unit Vector **x** has unit norm: \|\| x \|\| = 1

In [2]:
x = np.array([18, 3, 6])
x

array([18,  3,  6])

In [3]:
# L2 Norm
(18**2 + 3**2 + 6**2) ** (1/2)

19.209372712298546

In [4]:
# L2 Norm
np.linalg.norm(x)

19.209372712298546

In [5]:
def norm(v, p=2):
  t = np.sum([np.abs(x) ** p for x in v])
  return t ** (1/p)

In [6]:
norm(x)

19.209372712298546

$L^1$ Norm: \|\| x \|\|$_1$

In [7]:
x

array([18,  3,  6])

In [8]:
np.abs(18) + np.abs(3) + np.abs(6)

27

In [9]:
norm(x, p=1)

27.0

Squared $L^2$ Norm: \|\| x \|\|$^2_2$

Computationally cheaper to use than $L^2$ norm because


*   Squared $L^2$ norm equals simply **x$^2$x**
*   Derivative of element _x_ requires that element alone, whereas $L^2$ norm requires **x** vector



In [10]:
x

array([18,  3,  6])

In [11]:
(18**2 + 3**2 + 6**2)

369

In [12]:
np.dot(x, x)

369

In [13]:
x = np.array([[18, 3, 6]])
np.matmul(x, x.T)

array([[369]])

Max Norm ($L^\infty$ Norm): \|\| x \|\|$_\infty$

In [14]:
x = np.array([18, 3, 6])
x

array([18,  3,  6])

In [15]:
np.max([np.abs(18), np.abs(3), np.abs(6)])

18

In [16]:
def max_norm(v):
  return np.max([np.abs(x) for x in v])

In [17]:
max_norm(x)

18

Generalised $L^p$ Norm: \|\| x \|\|$_p$ , where $p \in \mathbb{R}$ and $p \geq 1$

$L^1$ and $L^2$ are particularly used to regularise objective functions.

In [18]:
def norm(v, p=2):
  t = np.sum([np.abs(x) ** p for x in v])
  return t ** (1/p)

Frobenius Norm

In [19]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [20]:
(1 ** 2 + 2 ** 2 + 3 ** 2 + 4 ** 2) ** (1 / 2)

5.477225575051661

In [21]:
np.linalg.norm(X)  # same function as for vector L2 norm

5.477225575051661

In [22]:
X_pt = torch.tensor([[1, 2], [3, 4.]])  # torch.norm() supports floats only

In [23]:
torch.norm(X_pt)

tensor(5.4772)

In [24]:
X_tf = tf.Variable([[1, 2], [3, 4.]])  # tf.norm() also supports floats only

In [25]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>