In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [3]:
col_1 = I[:, 0]
col_1

array([1, 0, 0])

In [4]:
col_2 = I[:, 1]
col_2

array([0, 1, 0])

In [5]:
col_3 = I[:, 2]
col_3

array([0, 0, 1])

Use dot product `np.dot()` method to prove each column of $I_3$ is orthogonal to each other.

In [6]:
np.dot(col_1, col_2)

0

In [7]:
np.dot(col_1, col_3)

0

In [8]:
np.dot(col_2, col_3)

0

Use `np.linalg.norm()` method to prove each column of $I_3$ has unit norm.

In [9]:
np.linalg.norm(col_1)

1.0

In [10]:
np.linalg.norm(col_2)

1.0

In [11]:
np.linalg.norm(col_3)

1.0

Since the matrix $I_3$ has mutually orthogonal columns and each column has unit norm, the column vectors of $I_3$ are orthonormal.

Also, since $I_3^T=I_3$, this means that rows of $I_3$ are orthonormal, $I_3$ is an orthogonal matrix.

In [12]:
K = torch.tensor([ [2/3, 1/3, 2/3], [-2/3, 2/3, 1/3], [1/3, 2/3, -2/3] ])
K

tensor([[ 0.6667,  0.3333,  0.6667],
        [-0.6667,  0.6667,  0.3333],
        [ 0.3333,  0.6667, -0.6667]])

In [13]:
K_col1 = K[:, 0]
K_col1

tensor([ 0.6667, -0.6667,  0.3333])

In [14]:
K_col2 = K[:, 1]
K_col2

tensor([0.3333, 0.6667, 0.6667])

In [15]:
K_col3 = K[:, 2]
K_col3

tensor([ 0.6667,  0.3333, -0.6667])

Prove columns of matrix K are mutually orthogonal

In [16]:
torch.dot(K_col1, K_col2)

tensor(0.)

In [17]:
torch.dot(K_col1, K_col3)

tensor(0.)

In [18]:
torch.dot(K_col3, K_col2)

tensor(0.)

Prove that every column of $K$ has unit norm

In [19]:
torch.norm(K_col1)

tensor(1.)

In [20]:
torch.norm(K_col2)

tensor(1.)

In [22]:
torch.norm(K_col3)

tensor(1.)

Determined that, in addition to being orthogonal, the columns of $K$ has unit norm, they therefore are orthonormal.

In [23]:
torch.matmul(K.T, K)

tensor([[ 1.0000e+00, -3.3114e-09,  3.3114e-09],
        [-3.3114e-09,  1.0000e+00,  6.6227e-09],
        [ 3.3114e-09,  6.6227e-09,  1.0000e+00]])

$K^TK=I$ has been confirmed and therefore $K$ is an orthogonal matrix.