In [2]:
import numpy as np

# np.outer()

1-D array

In [3]:
a = np.array([1,2,3,2,1])
b = np.array([0,2,4,6,8,1])

In [4]:
a.shape

(5,)

In [5]:
b.shape

(6,)

In [6]:
np.outer(a, b)

array([[ 0,  2,  4,  6,  8,  1],
       [ 0,  4,  8, 12, 16,  2],
       [ 0,  6, 12, 18, 24,  3],
       [ 0,  4,  8, 12, 16,  2],
       [ 0,  2,  4,  6,  8,  1]])

2-D array

np.outer() auto flatten arrays to 1-D arrays before computing

In [7]:
b = b.reshape(2, -1)
c = np.random.randint(0, 5, size=(2, 4))

In [8]:
b

array([[0, 2, 4],
       [6, 8, 1]])

In [9]:
c

array([[2, 4, 1, 4],
       [1, 1, 3, 3]])

In [10]:
np.outer(b, c)

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  8,  2,  8,  2,  2,  6,  6],
       [ 8, 16,  4, 16,  4,  4, 12, 12],
       [12, 24,  6, 24,  6,  6, 18, 18],
       [16, 32,  8, 32,  8,  8, 24, 24],
       [ 2,  4,  1,  4,  1,  1,  3,  3]])

In [11]:
# ravel(): flatten higher-dimensional array to 1-D array
np.outer(b.ravel(), c.ravel())

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  8,  2,  8,  2,  2,  6,  6],
       [ 8, 16,  4, 16,  4,  4, 12, 12],
       [12, 24,  6, 24,  6,  6, 18, 18],
       [16, 32,  8, 32,  8,  8, 24, 24],
       [ 2,  4,  1,  4,  1,  1,  3,  3]])