In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
X = np.array([[1,2], [3,4], [5,6]])
X_pt = torch.tensor([[1,2], [3,4], [5,6]])
X_tf = tf.Variable([[1,2], [3,4], [5,6]])

In [3]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
X.sum()

21

In [5]:
torch.sum(X_pt)

tensor(21)

In [6]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

Can also be done one specific axis alone

In [7]:
# summing over all rows
X.sum(axis=0)

array([ 9, 12])

In [8]:
# summing over all columns
X.sum(axis=1)

array([ 3,  7, 11])

In [9]:
torch.sum(X_pt, 0)

tensor([ 9, 12])

In [10]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  7, 11], dtype=int32)>

Other operations that can be applied with reduction along all or a selection of axes:

*   maximum
*   minimum
*   mean
*   product

