In [16]:
import numpy as np
import torch
import tensorflow as tf

In [17]:
X = np.array([[1, 2,], [3, 4], [5, 6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
X.T

array([[1, 3, 5],
       [2, 4, 6]])

In [19]:
X_pt = torch.from_numpy(X)
X_pt

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [20]:
X_pt.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [21]:
X_tf = tf.Variable([[1,2], [3,4], [5,6]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [22]:
tf.transpose(X_tf)  # less Pythonic

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>