In [1]:
import numpy as np
import torch
import tensorflow as tf

Vectors (Rank 1 Tensors) in NumPy

In [2]:
x = np.array([18, 3, 6]) # type argument is optional, e.g. dtype=np.float16
x

array([18,  3,  6])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0]  # zero-indexed

18

In [7]:
type(x[0])

numpy.int64

Vector Transposition

In [8]:
# Transposing a regular 1-D array has no effect.
x_t = x.T
x_t

array([18,  3,  6])

In [9]:
x_t.shape

(3,)

In [10]:
# But it does when we use nested "matrix-style" brackets
y = np.array([[18, 3, 6]])
y

array([[18,  3,  6]])

In [11]:
y.shape

(1, 3)

In [12]:
y_t = y.T
y_t

array([[18],
       [ 3],
       [ 6]])

In [13]:
y_t.shape

(3, 1)

In [14]:
y_t.T

array([[18,  3,  6]])

In [15]:
y_t.T.shape

(1, 3)

Zero Vectors

In [16]:
z = np.zeros(3)
z

array([0., 0., 0.])

Vectors in PyTorch and TensorFlow

In [17]:
x_pt = torch.tensor([18, 3, 6])
x_pt

tensor([18,  3,  6])

In [18]:
x_tf = tf.Variable([18, 3, 6])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([18,  3,  6], dtype=int32)>