In [1]:
import numpy as np

# np.median()

In [3]:
a = np.random.randint(100, size=(2, 3, 4))
a

array([[[24, 71, 53, 84],
        [74, 86, 76, 19],
        [93,  9, 88, 36]],

       [[47, 67, 47, 44],
        [54, 13, 40, 80],
        [95,  8, 55, 58]]])

In [4]:
np.median(a)

54.5

axis

In [5]:
np.median(a, axis=2)

array([[62. , 75. , 62. ],
       [47. , 47. , 56.5]])

In [6]:
np.median(a, axis=1)

array([[74., 71., 76., 36.],
       [54., 13., 47., 58.]])

overwrite_input

in-place overwrite arrays and perform faster calculation and better memory-usage efficiency

In [7]:
b = a.copy()
b

array([[[24, 71, 53, 84],
        [74, 86, 76, 19],
        [93,  9, 88, 36]],

       [[47, 67, 47, 44],
        [54, 13, 40, 80],
        [95,  8, 55, 58]]])

In [8]:
np.median(b, axis=1, overwrite_input=True)

array([[74., 71., 76., 36.],
       [54., 13., 47., 58.]])

In [9]:
np.all(a == b)

False

In [10]:
a

array([[[24, 71, 53, 84],
        [74, 86, 76, 19],
        [93,  9, 88, 36]],

       [[47, 67, 47, 44],
        [54, 13, 40, 80],
        [95,  8, 55, 58]]])

In [11]:
# b has been already in-place sorted
b

array([[[24,  9, 53, 19],
        [74, 71, 76, 36],
        [93, 86, 88, 84]],

       [[47,  8, 40, 44],
        [54, 13, 47, 58],
        [95, 67, 55, 80]]])

compare performance

In [20]:
a = np.random.randint(100, size=(20, 100, 50))
b = a.copy()

In [21]:
%timeit np.median(a, axis=1)

1.31 ms ± 34.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [22]:
%timeit np.median(b, axis=1, overwrite_input=True)

279 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [23]:
c = np.random.randint(0, 100, 1_000_000)
d = c.copy()

In [24]:
%timeit np.median(c)

9.64 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
%timeit np.median(d, overwrite_input=True)

2.66 ms ± 61.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


keepdims

In [27]:
a = np.random.randint(100, size=(2, 3, 4))
a

array([[[38, 67, 64, 91],
        [64, 94, 76, 73],
        [12, 99, 83,  2]],

       [[59,  1, 21,  0],
        [ 6, 64, 34, 82],
        [54, 15, 66, 85]]])

In [28]:
np.median(a, axis=0, keepdims=True)

array([[[48.5, 34. , 42.5, 45.5],
        [35. , 79. , 55. , 77.5],
        [33. , 57. , 74.5, 43.5]]])

In [31]:
np.median(a, axis=0, keepdims=False)

array([[48.5, 34. , 42.5, 45.5],
       [35. , 79. , 55. , 77.5],
       [33. , 57. , 74.5, 43.5]])

In [29]:
np.median(a, axis=1, keepdims=False)

array([[38., 94., 76., 73.],
       [54., 15., 34., 82.]])

In [30]:
np.median(a, axis=1, keepdims=True)

array([[[38., 94., 76., 73.]],

       [[54., 15., 34., 82.]]])