In [1]:
import numpy as np

# np.median()

In [3]:
a = np.random.randint(100, size=(2, 3, 4))
a

array([[[24, 71, 53, 84],
        [74, 86, 76, 19],
        [93,  9, 88, 36]],

       [[47, 67, 47, 44],
        [54, 13, 40, 80],
        [95,  8, 55, 58]]])

In [4]:
np.median(a)

54.5

axis

In [5]:
np.median(a, axis=2)

array([[62. , 75. , 62. ],
       [47. , 47. , 56.5]])

In [6]:
np.median(a, axis=1)

array([[74., 71., 76., 36.],
       [54., 13., 47., 58.]])

overwrite_input

in-place overwrite arrays and perform faster calculation and better memory-usage efficiency

In [7]:
b = a.copy()
b

array([[[24, 71, 53, 84],
        [74, 86, 76, 19],
        [93,  9, 88, 36]],

       [[47, 67, 47, 44],
        [54, 13, 40, 80],
        [95,  8, 55, 58]]])

In [8]:
np.median(b, axis=1, overwrite_input=True)

array([[74., 71., 76., 36.],
       [54., 13., 47., 58.]])

In [9]:
np.all(a == b)

False

In [10]:
a

array([[[24, 71, 53, 84],
        [74, 86, 76, 19],
        [93,  9, 88, 36]],

       [[47, 67, 47, 44],
        [54, 13, 40, 80],
        [95,  8, 55, 58]]])

In [11]:
# b has been already in-place sorted
b

array([[[24,  9, 53, 19],
        [74, 71, 76, 36],
        [93, 86, 88, 84]],

       [[47,  8, 40, 44],
        [54, 13, 47, 58],
        [95, 67, 55, 80]]])

compare performance

In [20]:
a = np.random.randint(100, size=(20, 100, 50))
b = a.copy()

In [21]:
%timeit np.median(a, axis=1)

1.31 ms ± 34.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [22]:
%timeit np.median(b, axis=1, overwrite_input=True)

279 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [23]:
c = np.random.randint(0, 100, 1_000_000)
d = c.copy()

In [24]:
%timeit np.median(c)

9.64 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
%timeit np.median(d, overwrite_input=True)

2.66 ms ± 61.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


keepdims

In [27]:
a = np.random.randint(100, size=(2, 3, 4))
a

array([[[38, 67, 64, 91],
        [64, 94, 76, 73],
        [12, 99, 83,  2]],

       [[59,  1, 21,  0],
        [ 6, 64, 34, 82],
        [54, 15, 66, 85]]])

In [28]:
np.median(a, axis=0, keepdims=True)

array([[[48.5, 34. , 42.5, 45.5],
        [35. , 79. , 55. , 77.5],
        [33. , 57. , 74.5, 43.5]]])

In [31]:
np.median(a, axis=0, keepdims=False)

array([[48.5, 34. , 42.5, 45.5],
       [35. , 79. , 55. , 77.5],
       [33. , 57. , 74.5, 43.5]])

In [29]:
np.median(a, axis=1, keepdims=False)

array([[38., 94., 76., 73.],
       [54., 15., 34., 82.]])

In [30]:
np.median(a, axis=1, keepdims=True)

array([[[38., 94., 76., 73.]],

       [[54., 15., 34., 82.]]])

# standard deviation

population std: $\sqrt{\frac{1}{N} \sum_{i=1}^N (x_i - \overline{x})^2}$

sample std: $\sqrt{\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2}$

In [32]:
a = np.random.rand(10)
a

array([0.97156925, 0.23688448, 0.96168896, 0.62734688, 0.98607823,
       0.49120216, 0.25425672, 0.11026693, 0.50946712, 0.37337623])

In [33]:
np.std(a)

0.3095921259845588

axis

In [34]:
b = np.random.rand(2, 3, 4)
b

array([[[0.20349596, 0.51392328, 0.35590893, 0.85844314],
        [0.64164078, 0.31586939, 0.42695997, 0.10151447],
        [0.03096796, 0.49711576, 0.22151826, 0.14247933]],

       [[0.29052292, 0.12191408, 0.99391488, 0.8334914 ],
        [0.94657471, 0.57168988, 0.1081739 , 0.22209168],
        [0.39008847, 0.50533202, 0.48402749, 0.18007978]]])

In [35]:
np.std(b, axis=0)

array([[0.04351348, 0.1960046 , 0.31900298, 0.01247587],
       [0.15246696, 0.12791024, 0.15939303, 0.06028861],
       [0.17956026, 0.00410813, 0.13125461, 0.01880023]])

ddof: delta degrees of freedom

In [36]:
# default ddof = 0
# population std
np.std(b)

0.27379067355427883

In [37]:
# sample std: ddof = 1
np.std(b, ddof=1)

0.2796793187086997

# variance

Population Var = $\frac{1}{N} \sum_{i=1}^N (x_i - \overline{x})^2$

Sample Var = $\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2$

In [38]:
a = np.array([10, 20, 12, 0, 3, 5])
a

array([10, 20, 12,  0,  3,  5])

In [39]:
np.var(a)

43.55555555555555

# covariance

Population Cov = $\frac{1}{N} \sum_{i=1}^N (x_i - \overline{x})(y_i - \overline{y})$

Sample Cov = $\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})(y_i - \overline{y})$

In [40]:
a = np.array([
    [10, 5, 2, 4, 9, 3, 2],
    [10, 2, 8, 3, 7, 4, 1]
])
a

array([[10,  5,  2,  4,  9,  3,  2],
       [10,  2,  8,  3,  7,  4,  1]])

covariance matrix

In [41]:
np.cov(a)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [42]:
c = np.array([3, 2, 1, 5, 7, 2, 1])
np.cov(a, c)

array([[10.66666667,  6.66666667,  4.66666667],
       [ 6.66666667, 11.33333333,  1.66666667],
       [ 4.66666667,  1.66666667,  5.        ]])

bias

In [43]:
# default bias=False
# sample covariance: unbiased estimator
np.cov(a, bias=False)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [44]:
np.cov(a, bias=True)

array([[9.14285714, 5.71428571],
       [5.71428571, 9.71428571]])

ddof

In [46]:
np.cov(a, ddof=None)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [47]:
np.cov(a, ddof=1)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [48]:
np.cov(a, ddof=0)

array([[9.14285714, 5.71428571],
       [5.71428571, 9.71428571]])

fweights: frequency weights

In [49]:
a

array([[10,  5,  2,  4,  9,  3,  2],
       [10,  2,  8,  3,  7,  4,  1]])

In [50]:
fweights = np.array([1, 2, 2, 1, 1, 1, 1])

In [52]:
# The pairs (5, 2) and (2, 8) will repeated twice before calculation
np.cov(a, fweights=fweights)

array([[ 9.   ,  3.875],
       [ 3.875, 10.75 ]])

aweights: array of weights

In [53]:
aweights = np.array([0.1, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1])

In [54]:
np.cov(a, aweights=None)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [55]:
np.cov(a, aweights=aweights)

array([[ 8.61904762,  3.83333333],
       [ 3.83333333, 10.66666667]])

# correlation coefficients

$r = \frac{S_{XY}}{S_{X}S_{Y}}$

In [56]:
x = np.array([
    [1,2,1,9,10,3,2,6,7],
    [2,1,8,3,7,5,10,7,2]
])
x

array([[ 1,  2,  1,  9, 10,  3,  2,  6,  7],
       [ 2,  1,  8,  3,  7,  5, 10,  7,  2]])

In [57]:
# return correlation coefficient matrix
np.corrcoef(x)

array([[ 1.        , -0.05640533],
       [-0.05640533,  1.        ]])

In [58]:
y = np.array([2, 1, 1, 8, 9, 4, 3, 5, 7])

In [59]:
np.corrcoef(x, y)

array([[ 1.        , -0.05640533,  0.97094584],
       [-0.05640533,  1.        , -0.01315587],
       [ 0.97094584, -0.01315587,  1.        ]])

rowvar

In [60]:
np.corrcoef(x, rowvar=False)

array([[ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.]])

In [61]:
x_transpose = x.T

In [62]:
np.corrcoef(x_transpose, rowvar=False)

array([[ 1.        , -0.05640533],
       [-0.05640533,  1.        ]])

In [63]:
np.corrcoef(x_transpose, rowvar=True)

array([[ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.]])